### ISSUE TITLE
Create Experiment Meta Data object

### ISSUE THREAD

**Issue by janneskasper** [pascalbenschopTU/NovelEnvironments#54]
- [x] Share the data object with other scenes
- [x] Include participant number
- [x] include date
- [x] include experiment configuration
- [x] include Seed used for generating
